package io.base14.scout.core.semantics

object ScoutAttributes {
    const val SESSION_ID = "session.id"
    const val SESSION_TYPE = "session.type"
    const val SESSION_SAMPLE_RATE = "session.sample_rate"
    const val SESSION_SAMPLED = "session.sampled"
    const val SESSION_START_TIME = "session.start_time"
    const val SESSION_PREVIOUS_ID = "session.previous_id"

    const val USER_ID = "user.id"
    const val USER_ANONYMOUS_ID = "user.anonymous_id"

    const val SCREEN_NAME = "screen.name"
    const val SCREEN_LOAD_TIME = "screen.load_time"
    const val VIEW_ID = "view.id"
    const val VIEW_LOADING_TYPE = "view.loading_type"
    const val VIEW_IS_ACTIVE = "view.is_active"
    const val VIEW_REFERRER = "view.referrer"
    const val VIEW_TIME_SPENT = "view.time_spent"

    const val APP_STARTUP_TYPE = "app_startup.type"
    const val APP_STARTUP_DURATION = "app_startup.duration"

    const val APP_LIFECYCLE_ID = "app_lifecycle.id"
    const val APP_LIFECYCLE_STATE = "app_lifecycle.state"
    const val APP_LIFECYCLE_PREVIOUS_STATE = "app_lifecycle.previous_state"
    const val APP_LIFECYCLE_TIMESTAMP = "app_lifecycle.timestamp"

    const val UI_ID = "user_interaction.id"
    const val UI_TYPE = "user_interaction.type"
    const val UI_TARGET = "user_interaction.target"
    const val UI_TARGET_TYPE = "user_interaction.target.type"
    const val UI_TARGET_NAME_SOURCE = "user_interaction.target.name_source"
    const val UI_TARGET_PERMANENT_ID = "user_interaction.target.permanent_id"
    const val UI_TARGET_X = "user_interaction.target.x"
    const val UI_TARGET_Y = "user_interaction.target.y"

    const val HTTP_METHOD = "http.request.method"
    const val URL_FULL = "url.full"
    const val HTTP_STATUS_CODE = "http.response.status_code"
    const val HTTP_BODY_SIZE = "http.response.body.size"
    const val HTTP_ROUTE = "http.route"
    const val HTTP_DURATION_MS = "http.duration_ms"
    const val HTTP_ERROR = "http.error"

    const val ERROR_ID = "error.id"
    const val ERROR_TYPE = "error.type"
    const val ERROR_MESSAGE = "error.message"
    const val ERROR_STACK_TRACE = "error.stack_trace"
    const val ERROR_HANDLED = "error.handled"
    const val ERROR_HANDLING = "error.handling"
    const val ERROR_SOURCE = "error.source"
    const val ERROR_SOURCE_TYPE = "error.source_type"
    const val ERROR_FINGERPRINT = "error.fingerprint"
    const val ERROR_TIME_SINCE_APP_START_MS = "error.time_since_app_start_ms"
    const val BREADCRUMBS = "breadcrumbs"

    const val CRASH_TYPE = "crash.type"
    const val CRASH_REASON = "crash.reason"
    const val CRASH_TIMESTAMP = "crash.timestamp"
    const val CRASH_STACK_TRACE = "crash.stack_trace"
    const val CRASH_LAST_SCREEN = "crash.last_screen"
    const val CRASH_PREVIOUS_SESSION_ID = "crash.previous_session_id"
    const val CRASH_STARTED_AT = "crash.started_at"
    const val CRASH_STATUS = "crash.status"
    const val CRASH_THREAD_NAME = "crash.thread_name"
    const val CRASH_SIGNAL = "crash.signal"
    const val CRASH_SIGNAL_NUMBER = "crash.signal_number"

    const val ANR_DURATION = "anr.duration"
    const val ANR_THRESHOLD = "anr.threshold"
    const val ANR_MAIN_THREAD_STACK = "anr.main_thread_stack"
    const val ANR_THREADS_JSON = "anr.threads_json"
    const val ANR_THREAD_COUNT = "anr.thread_count"
    const val LONG_TASK_DURATION = "long_task.duration"
    const val LONG_TASK_THRESHOLD = "long_task.threshold"
    const val FROZEN_FRAME_DURATION = "frozen_frame.duration"

    const val VITAL_NAME = "vital.name"
    const val VITAL_DURATION = "vital.duration"
    const val VITAL_DURATION_MS = "vital.duration_ms"
    const val VITAL_TYPE = "vital.type"
    const val VITAL_FROM_SCREEN = "vital.from_screen"
    const val VITAL_TO_SCREEN = "vital.to_screen"
}

object ScoutResourceAttributes {
    const val SERVICE_NAME = "service.name"
    const val SERVICE_VERSION = "service.version"
    const val ENVIRONMENT = "environment"
    const val APP_BUNDLE_ID = "app.bundle_id"
    const val APP_VERSION = "app.version"
    const val APP_BUILD = "app.build"
    const val OS_NAME = "os.name"
    const val OS_VERSION = "os.version"
    const val OS_BUILD = "os.build"
    const val HOST_ARCH = "host.arch"
    const val DEVICE_TYPE = "device.type"
    const val DEVICE_NAME = "device.name"
    const val DEVICE_MODEL_NAME = "device.model.name"
    const val DEVICE_MANUFACTURER = "device.manufacturer"
    const val DEVICE_BRAND = "device.brand"
    const val DEVICE_IS_PHYSICAL = "device.is_physical"
    const val DEVICE_LOCALE = "device.locale"
    const val DEVICE_TIMEZONE = "device.timezone"
    const val DEVICE_BATTERY_LEVEL = "device.battery.level"
    const val DEVICE_BATTERY_STATE = "device.battery.state"
    const val NETWORK_CONNECTION_TYPE = "network.connection.type"
}
